#ifndef COM_GSCHAT_SERVICE_GS
#define COM_GSCHAT_SERVICE_GS
#import <com/gsrpc/channel.h>

#import <com/gsrpc/stream.h>


@class GSNamedService;


// GSNamedService generated by objrpc tools
@interface GSNamedService : NSObject

@property(nonatomic, strong) NSString* Name;

@property GSServiceType Type;

@property UInt32 VNodes;

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
@end



//GSService generate by objrpc
@protocol GSService<NSObject>

- (GSNamedService*) Name;

@end

// GSServiceService generate by objrpc
@interface GSServiceService : NSObject<GSDispatcher>
+ (instancetype) init:(id<GSService>)service withID:(UInt16) serviceID;

@property(readonly) UInt16 ID;

- (GSResponse *)Dispatch:(GSRequest *)call;

@end


@interface GSServiceRPC : NSObject
+ (instancetype) initRPC:(id<GSChannel>) channel withID:(UInt16) serviceID;

- (id<GSPromise>) Name;

@end



//GSIManager generate by objrpc
@protocol GSIManager<NSObject>

- (void) Bind:(NSString*)arg0 withArg1:(GSDevice*)arg1;

- (void) Unbind:(NSString*)arg0 withArg1:(GSDevice*)arg1;

@end

// GSIManagerService generate by objrpc
@interface GSIManagerService : NSObject<GSDispatcher>
+ (instancetype) init:(id<GSIManager>)service withID:(UInt16) serviceID;

@property(readonly) UInt16 ID;

- (GSResponse *)Dispatch:(GSRequest *)call;

@end


@interface GSIManagerRPC : NSObject
+ (instancetype) initRPC:(id<GSChannel>) channel withID:(UInt16) serviceID;

- (id<GSPromise>) Bind:(NSString*) arg0  withArg1:(GSDevice*) arg1 ;

- (id<GSPromise>) Unbind:(NSString*) arg0  withArg1:(GSDevice*) arg1 ;

@end


#endif //COM_GSCHAT_SERVICE_GS
